// Doğruluk mu Cesaret mi? — genel/aile dostu, herkesin oynayabileceği sorular ve görevler.
export const TRUTH_QUESTIONS: readonly string[] = [
  'En garip alışkanlığın nedir?',
  'İlk aşkının adı neydi?',
  'Hayatındaki en utanç verici anı nedir?',
  'Bir günlüğüne birinin yerine geçebilseydin kim olurdun?',
  'En büyük korkun nedir?',
  'Şu ana kadar söylediğin en büyük yalan nedir?',
  'Telefonunda sildiğin en garip fotoğraf ne olabilir?',
  'Kimseye söylemediğin bir yeteneğin var mı?',
  'En son ne zaman ağladın ve neden?',
  'Bu odadaki biriyle takas yapman gerekse kiminle yapardın?',
  'En çok pişman olduğun karar nedir?',
  'Gizlice hayranı olduğun biri var mı?',
  'Okulda/işte en büyük başın belaya girdiği an neydi?',
  'Kendinle ilgili değiştirmek istediğin bir şey nedir?',
  'En tuhaf rüyanı anlat.',
  'Şu an telefonunda en çok kimle yazışıyorsun?',
  'Hayatında hiç kimseye itiraf etmediğin bir şey var mı?',
  'En son ne zaman gerçekten çok utandın?',
  'İlk iş mülakatında/sınavda yaptığın en büyük gaf neydi?',
  'Bir daha asla yapmayacağını söylediğin ama tekrar yaptığın bir şey var mı?',
  'Şu anki en büyük hayalin nedir?',
  'Bir gecede zengin olsan ilk yapacağın şey ne olurdu?',
  'Hayatında en çok güvendiğin kişi kim ve neden?',
  'Kendinle gurur duyduğun bir an anlat.',
  'En kötü randevu deneyimin neydi?',
  'Bir arkadaşınla en çok neden tartışırsın?',
  'Kıskançlığın en çok tetiklendiği durum nedir?',
  'Bugüne kadar aldığın en garip hediye neydi?',
  'Sosyal medyada kimi gizlice takip ediyorsun ama beğenmiyorsun?',
  'En çok özlediğin dönem hangisi?',
  'Hayatında hiç "keşke söylemeseydim" dediğin bir cümle oldu mu?',
  'En son ne zaman birine yalan söyledin ve neden?',
  'Bir konuda tamamen yanıldığını fark ettiğin bir an anlat.',
  'Seni en çok kim kızdırır ve nasıl?',
  'Küçükken en çok neyden korkardın?',
  'Şu an odadaki biri hakkında düşündüğün ama söylemediğin bir şey var mı?',
  'En tuhaf yeme alışkanlığın nedir?',
  'Bugüne kadar aldığın en kötü karar neydi?',
  'Bir günlüğüne görünmez olsan ne yapardın?',
  'En çok kime özenirsin?',
  'Hayatta seni en çok değiştiren olay neydi?',
  'En son ne zaman birine "seni seviyorum" demedin ama demen gerekiyordu?',
  'Telefon rehberinde en garip kayıtlı isim hangisi?',
  'Bir daha yaşamak isteyeceğin bir gün hangisi olurdu?',
  'En çok utandığın fiziksel özelliğin nedir?',
  'Hiç birinin yerine kararı sen mi verdin, sonra pişman mı oldun?',
  'Arkadaş grubunda sana takılan bir lakap var mı, nereden geldi?',
  'En son ne zaman "olmasa da olur" dediğin bir şeye çok para harcadın?',
  'Bir ilişkide seni en çok ne rahatsız eder?',
  'İlk öpücüğün nasıldı, kısaca anlat.',
  'Hayatında en çok kıskandığın kişi kim?',
];

export const DARE_CHALLENGES: readonly string[] = [
  '30 saniye boyunca komik bir sesle konuş.',
  'En sevdiğin şarkıdan bir dize seslice söyle.',
  'Sıradaki tura kadar herkese "kral/kraliçe" diye hitap et.',
  'Bir hayvan taklidi yap, herkes tahmin etsin.',
  '10 saniye boyunca hiç gülmeden ciddi bir surat yap.',
  'Odadaki birine içten bir iltifat et.',
  'Son çektiğin fotoğrafı göster (uygunsa).',
  'Bir tekerleme söyle, yanlış söylersen tekrar dene.',
  'Gözlerin kapalı, 15 saniye tek ayak üstünde dur.',
  'En son attığın mesajı yüksek sesle oku (uygunsa).',
  'Kendine özel bir "giriş müziği" mırıldan.',
  'Sıradaki oyuncuya 3 soruluk bir "röportaj" yap.',
  'Elini çenene koyup 20 saniye "düşünen adam" pozu ver.',
  'Bir ünlüyü taklit et, herkes tahmin etsin.',
  'Tersten 10\'dan geriye say, yanlış yaparsan baştan başla.',
  'Odadaki birine komik bir lakap tak, tur boyunca öyle çağır.',
  'Bir spor spikeri gibi son yediğin yemeği anlat.',
  'Alfabeyle sırayla 10 hayvan ismi say, takılırsan baştan başla.',
  'Bir reklam filmi gibi yanındaki bir eşyayı "sat".',
  '20 saniye boyunca robot gibi konuş ve hareket et.',
  'Sıradaki oyuncunun sesini/aksanını taklit ederek bir cümle kur.',
  'Gözlerini kapatıp burnuna dokunmaya çalış, 3 kere dene.',
  'Bir haber spikeri ciddiyetiyle saçma bir "son dakika" haberi uydur.',
  'Telefonundaki son arama geçmişinden bir ismi söyle (uygunsa).',
  'Karşındaki kişiyle 10 saniye göz teması kur, gülersen baştan başla.',
  'Kendi adını geriye doğru söylemeye çalış.',
  'Bir şarkının nakaratını sadece "na na na" diyerek söyle, herkes tahmin etsin.',
  'Elinle çenen arasına telefon sıkıştırıp 15 saniye konuş.',
  'Bir tiyatro oyuncusu edasıyla "bugün çok yoruldum" cümlesini abartarak söyle.',
  'Sıradaki oyuncuya komik bir soru sor, o da doğaçlama cevap versin.',
  'Bir dakika boyunca sadece soru cümleleriyle konuş.',
  'Gözlerin kapalı, sesten sıradaki oyuncunun kim olduğunu tahmin et.',
  'Kendine ait en absürt bir "süper güç" uydur ve anlat.',
  'Bir spor yorumcusu gibi kendi yediğin son atıştırmalığı yorumla.',
  'Parmaklarınla masaya/ekrana bir ritim tut, herkes şarkıyı tahmin etsin.',
  'Bir cümleyi sadece emoji sesleriyle (bip, çat, tak) anlatmaya çalış.',
  'Elini kaldırıp "ben" diyerek en son yaptığın garip şeyi itiraf et.',
  'Bir dizi/film karakteri gibi konuşarak "naber" sor, herkes tahmin etsin.',
  '15 saniye boyunca yalnızca fısıldayarak konuş.',
  'Sıradaki oyuncuya taklit edeceğin bir meslek söyle, o meslek gibi 10 saniye konuş.',
];
