export type FiveSecondDifficulty = 'easy' | 'medium' | 'hard' | 'chaos';
export type FiveSecondCategory = 'geography' | 'sports' | 'entertainment' | 'music' | 'food' | 'tech' | 'social';

export type FiveSecondChallenge = {
  id: string;
  difficulty: FiveSecondDifficulty;
  category: FiveSecondCategory;
  tr: string;
  en: string;
};

export const FIVE_SECOND_CHALLENGES: FiveSecondChallenge[] = [
  // ---------------------------------------------------------------------
  // EASY
  // ---------------------------------------------------------------------
  { id: 'easy_1', difficulty: 'easy', category: 'geography', tr: "5 saniyede A harfiyle başlayan 3 ülke söyle.", en: 'Name 3 countries that start with the letter A.' },
  { id: 'easy_2', difficulty: 'easy', category: 'geography', tr: '5 saniyede 3 Avrupa ülkesi söyle.', en: 'Name 3 European countries.' },
  { id: 'easy_3', difficulty: 'easy', category: 'geography', tr: '5 saniyede 3 başkent söyle.', en: 'Name 3 capital cities.' },
  { id: 'easy_4', difficulty: 'easy', category: 'geography', tr: '5 saniyede 3 ada ülkesi söyle.', en: 'Name 3 island countries.' },
  { id: 'easy_5', difficulty: 'easy', category: 'geography', tr: '5 saniyede 3 sıcak ülke söyle.', en: 'Name 3 hot countries.' },
  { id: 'easy_6', difficulty: 'easy', category: 'geography', tr: '5 saniyede 3 Avrupa şehri söyle.', en: 'Name 3 European cities.' },
  { id: 'easy_7', difficulty: 'easy', category: 'geography', tr: "5 saniyede İstanbul'da 3 ilçe söyle.", en: 'Name 3 districts in Istanbul.' },
  { id: 'easy_8', difficulty: 'easy', category: 'geography', tr: "5 saniyede Londra'da 3 yer söyle.", en: 'Name 3 places in London.' },
  { id: 'easy_9', difficulty: 'easy', category: 'sports', tr: '5 saniyede 3 futbolcu söyle.', en: 'Name 3 footballers.' },
  { id: 'easy_10', difficulty: 'easy', category: 'sports', tr: '5 saniyede 3 Premier League takımı söyle.', en: 'Name 3 Premier League teams.' },
  { id: 'easy_11', difficulty: 'easy', category: 'sports', tr: '5 saniyede 3 Süper Lig takımı söyle.', en: 'Name 3 Turkish Süper Lig teams.' },
  { id: 'easy_12', difficulty: 'easy', category: 'sports', tr: '5 saniyede 3 futbol pozisyonu söyle.', en: 'Name 3 football positions.' },
  { id: 'easy_13', difficulty: 'easy', category: 'sports', tr: '5 saniyede 3 spor dalı söyle.', en: 'Name 3 sports.' },
  { id: 'easy_14', difficulty: 'easy', category: 'entertainment', tr: '5 saniyede 3 film söyle.', en: 'Name 3 movies.' },
  { id: 'easy_15', difficulty: 'easy', category: 'entertainment', tr: '5 saniyede 3 Netflix dizisi söyle.', en: 'Name 3 Netflix shows.' },
  { id: 'easy_16', difficulty: 'easy', category: 'entertainment', tr: '5 saniyede 3 süper kahraman söyle.', en: 'Name 3 superheroes.' },
  { id: 'easy_17', difficulty: 'easy', category: 'music', tr: '5 saniyede 3 rapçi söyle.', en: 'Name 3 rappers.' },
  { id: 'easy_18', difficulty: 'easy', category: 'music', tr: '5 saniyede 3 kadın şarkıcı söyle.', en: 'Name 3 female singers.' },
  { id: 'easy_19', difficulty: 'easy', category: 'tech', tr: '5 saniyede 3 otomobil markası söyle.', en: 'Name 3 car brands.' },
  { id: 'easy_20', difficulty: 'easy', category: 'tech', tr: '5 saniyede 3 lüks marka söyle.', en: 'Name 3 luxury brands.' },
  { id: 'easy_21', difficulty: 'easy', category: 'tech', tr: '5 saniyede 3 sosyal medya uygulaması söyle.', en: 'Name 3 social media apps.' },
  { id: 'easy_22', difficulty: 'easy', category: 'tech', tr: '5 saniyede 3 mesajlaşma uygulaması söyle.', en: 'Name 3 messaging apps.' },
  { id: 'easy_23', difficulty: 'easy', category: 'food', tr: '5 saniyede 3 Türk yemeği söyle.', en: 'Name 3 Turkish dishes.' },
  { id: 'easy_24', difficulty: 'easy', category: 'food', tr: '5 saniyede 3 Türk tatlısı söyle.', en: 'Name 3 Turkish desserts.' },
  { id: 'easy_25', difficulty: 'easy', category: 'food', tr: '5 saniyede 3 fast food yemeği söyle.', en: 'Name 3 fast food items.' },
  { id: 'easy_26', difficulty: 'easy', category: 'food', tr: '5 saniyede 3 meyve söyle.', en: 'Name 3 fruits.' },
  { id: 'easy_27', difficulty: 'easy', category: 'food', tr: '5 saniyede 3 sıcak içecek söyle.', en: 'Name 3 hot drinks.' },
  { id: 'easy_28', difficulty: 'easy', category: 'food', tr: '5 saniyede 3 kahvaltılık söyle.', en: 'Name 3 breakfast foods.' },
  { id: 'easy_29', difficulty: 'easy', category: 'social', tr: '5 saniyede 3 date fikri söyle.', en: 'Name 3 date ideas.' },
  { id: 'easy_30', difficulty: 'easy', category: 'social', tr: '5 saniyede hafta sonu yapılabilecek 3 şey söyle.', en: 'Name 3 things you can do on a weekend.' },

  // ---------------------------------------------------------------------
  // MEDIUM
  // ---------------------------------------------------------------------
  { id: 'medium_1', difficulty: 'medium', category: 'geography', tr: "5 saniyede Avrupa'da denize kıyısı olmayan 3 ülke söyle.", en: 'Name 3 landlocked European countries.' },
  { id: 'medium_2', difficulty: 'medium', category: 'geography', tr: '5 saniyede başkenti ülke adıyla aynı olmayan 3 ülke söyle.', en: "Name 3 countries whose capital isn't the same as the country's name." },
  { id: 'medium_3', difficulty: 'medium', category: 'geography', tr: '5 saniyede iki kelimelik 3 ülke adı söyle.', en: 'Name 3 two-word country names.' },
  { id: 'medium_4', difficulty: 'medium', category: 'geography', tr: "5 saniyede Akdeniz'e kıyısı olan 3 ülke söyle.", en: 'Name 3 countries on the Mediterranean.' },
  { id: 'medium_5', difficulty: 'medium', category: 'geography', tr: '5 saniyede bayrağında yıldız bulunan 3 ülke söyle.', en: 'Name 3 countries with a star on their flag.' },
  { id: 'medium_6', difficulty: 'medium', category: 'geography', tr: '5 saniyede bayrağında kırmızı ve beyaz bulunan 3 ülke söyle.', en: 'Name 3 countries with red and white on their flag.' },
  { id: 'medium_7', difficulty: 'medium', category: 'geography', tr: "5 saniyede Türkiye'ye komşu 3 ülke söyle.", en: 'Name 3 countries that border Turkey.' },
  { id: 'medium_8', difficulty: 'medium', category: 'geography', tr: "5 saniyede Almanya'ya komşu 3 ülke söyle.", en: 'Name 3 countries that border Germany.' },
  { id: 'medium_9', difficulty: 'medium', category: 'geography', tr: "5 saniyede Fransa'ya komşu 3 ülke söyle.", en: 'Name 3 countries that border France.' },
  { id: 'medium_10', difficulty: 'medium', category: 'sports', tr: "5 saniyede Dünya Kupası kazanmış 3 Avrupa ülkesi söyle.", en: 'Name 3 European countries that have won the World Cup.' },
  { id: 'medium_11', difficulty: 'medium', category: 'geography', tr: "5 saniyede İngiltere'de Londra dışında 3 şehir söyle.", en: 'Name 3 cities in England other than London.' },
  { id: 'medium_12', difficulty: 'medium', category: 'geography', tr: '5 saniyede metro sistemi olan 3 Avrupa şehri söyle.', en: 'Name 3 European cities with a metro system.' },
  { id: 'medium_13', difficulty: 'medium', category: 'geography', tr: "5 saniyede Ege Bölgesi'nde 3 şehir söyle.", en: 'Name 3 cities in the Aegean Region.' },
  { id: 'medium_14', difficulty: 'medium', category: 'geography', tr: "5 saniyede Karadeniz'e kıyısı olan 3 Türk şehri söyle.", en: 'Name 3 Turkish cities on the Black Sea.' },
  { id: 'medium_15', difficulty: 'medium', category: 'geography', tr: "5 saniyede İstanbul'un Avrupa Yakası'nda 3 ilçe söyle.", en: "Name 3 districts on Istanbul's European side." },
  { id: 'medium_16', difficulty: 'medium', category: 'geography', tr: "5 saniyede İstanbul'un Anadolu Yakası'nda 3 ilçe söyle.", en: "Name 3 districts on Istanbul's Asian side." },
  { id: 'medium_17', difficulty: 'medium', category: 'geography', tr: "5 saniyede Boğaz'a kıyısı olan 3 İstanbul ilçesi söyle.", en: 'Name 3 Istanbul districts on the Bosphorus.' },
  { id: 'medium_18', difficulty: 'medium', category: 'geography', tr: "5 saniyede Türkiye'de nüfusu 1 milyondan fazla 3 şehir söyle.", en: 'Name 3 Turkish cities with a population over 1 million.' },
  { id: 'medium_19', difficulty: 'medium', category: 'sports', tr: '5 saniyede olimpiyat düzenlemiş 3 şehir söyle.', en: 'Name 3 cities that have hosted the Olympics.' },
  { id: 'medium_20', difficulty: 'medium', category: 'geography', tr: "5 saniyede Akdeniz'e kıyısı olan 3 Afrika ülkesi söyle.", en: 'Name 3 African countries on the Mediterranean.' },
  { id: 'medium_21', difficulty: 'medium', category: 'sports', tr: "5 saniyede Londra'da bulunan 3 futbol kulübü söyle.", en: 'Name 3 football clubs based in London.' },
  { id: 'medium_22', difficulty: 'medium', category: 'sports', tr: "5 saniyede Şampiyonlar Ligi kazanmış 3 İngiliz takımı söyle.", en: 'Name 3 English teams that have won the Champions League.' },
  { id: 'medium_23', difficulty: 'medium', category: 'sports', tr: "5 saniyede Ballon d'Or kazanmış 3 futbolcu söyle.", en: 'Name 3 Ballon d’Or winners.' },
  { id: 'medium_24', difficulty: 'medium', category: 'sports', tr: "5 saniyede Cristiano Ronaldo'nun oynadığı 3 kulüp söyle.", en: 'Name 3 clubs Cristiano Ronaldo has played for.' },
  { id: 'medium_25', difficulty: 'medium', category: 'sports', tr: '5 saniyede Messi ile aynı takımda oynamış 3 futbolcu söyle.', en: 'Name 3 footballers who have played on the same team as Messi.' },
  { id: 'medium_26', difficulty: 'medium', category: 'sports', tr: "5 saniyede Premier League'de oynamış 3 Türk futbolcu söyle.", en: 'Name 3 Turkish footballers who have played in the Premier League.' },
  { id: 'medium_27', difficulty: 'medium', category: 'sports', tr: "5 saniyede Barcelona'da oynamış 3 Brezilyalı futbolcu söyle.", en: 'Name 3 Brazilian footballers who have played for Barcelona.' },
  { id: 'medium_28', difficulty: 'medium', category: 'sports', tr: "5 saniyede Real Madrid'de oynamış 3 Fransız futbolcu söyle.", en: 'Name 3 French footballers who have played for Real Madrid.' },
  { id: 'medium_29', difficulty: 'medium', category: 'sports', tr: "5 saniyede Mourinho'nun çalıştırdığı 3 takım söyle.", en: 'Name 3 teams Mourinho has managed.' },
  { id: 'medium_30', difficulty: 'medium', category: 'sports', tr: "5 saniyede Guardiola'nın çalıştırdığı 3 takım söyle.", en: 'Name 3 teams Guardiola has managed.' },
  { id: 'medium_31', difficulty: 'medium', category: 'sports', tr: '5 saniyede forması kırmızı olan 3 futbol takımı söyle.', en: 'Name 3 football teams with red shirts.' },
  { id: 'medium_32', difficulty: 'medium', category: 'sports', tr: '5 saniyede forması mavi olan 3 futbol takımı söyle.', en: 'Name 3 football teams with blue shirts.' },
  { id: 'medium_33', difficulty: 'medium', category: 'sports', tr: "5 saniyede İstanbul'da bulunan 3 futbol kulübü söyle.", en: 'Name 3 football clubs based in Istanbul.' },
  { id: 'medium_34', difficulty: 'medium', category: 'sports', tr: "5 saniyede Türkiye'de oynamış 3 dünyaca ünlü futbolcu söyle.", en: 'Name 3 world-famous footballers who have played in Turkey.' },
  { id: 'medium_35', difficulty: 'medium', category: 'sports', tr: '5 saniyede Dünya Kupası finalinde oynamış 3 ülke söyle.', en: 'Name 3 countries that have played in a World Cup final.' },
  { id: 'medium_36', difficulty: 'medium', category: 'sports', tr: '5 saniyede raketle oynanan 3 spor söyle.', en: 'Name 3 racket sports.' },
  { id: 'medium_37', difficulty: 'medium', category: 'sports', tr: '5 saniyede su içinde yapılan 3 spor söyle.', en: 'Name 3 water sports.' },
  { id: 'medium_38', difficulty: 'medium', category: 'sports', tr: '5 saniyede top kullanılmayan 3 spor söyle.', en: "Name 3 sports that don't use a ball." },
  { id: 'medium_39', difficulty: 'medium', category: 'sports', tr: '5 saniyede 3 dövüş sporu söyle.', en: 'Name 3 combat sports.' },
  { id: 'medium_40', difficulty: 'medium', category: 'sports', tr: '5 saniyede 3 motor sporu söyle.', en: 'Name 3 motorsports.' },
  { id: 'medium_41', difficulty: 'medium', category: 'entertainment', tr: '5 saniyede Oscar kazanmış 3 oyuncu söyle.', en: 'Name 3 Oscar-winning actors.' },
  { id: 'medium_42', difficulty: 'medium', category: 'entertainment', tr: "5 saniyede Leonardo DiCaprio'nun oynadığı 3 film söyle.", en: 'Name 3 movies Leonardo DiCaprio has starred in.' },
  { id: 'medium_43', difficulty: 'medium', category: 'entertainment', tr: "5 saniyede Christopher Nolan'ın 3 filmini söyle.", en: 'Name 3 Christopher Nolan movies.' },
  { id: 'medium_44', difficulty: 'medium', category: 'entertainment', tr: "5 saniyede Netflix'te yayınlanmış 3 popüler dizi söyle.", en: 'Name 3 popular shows that aired on Netflix.' },
  { id: 'medium_45', difficulty: 'medium', category: 'entertainment', tr: "5 saniyede Marvel'dan 3 kötü karakter söyle.", en: 'Name 3 Marvel villains.' },
  { id: 'medium_46', difficulty: 'medium', category: 'entertainment', tr: '5 saniyede başrolünde kadın olan 3 dizi söyle.', en: 'Name 3 shows with a female lead.' },
  { id: 'medium_47', difficulty: 'medium', category: 'entertainment', tr: "5 saniyede 2000'den önce çıkmış 3 ünlü film söyle.", en: 'Name 3 famous movies released before 2000.' },
  { id: 'medium_48', difficulty: 'medium', category: 'entertainment', tr: '5 saniyede tek kelimelik 3 film adı söyle.', en: 'Name 3 one-word movie titles.' },
  { id: 'medium_49', difficulty: 'medium', category: 'entertainment', tr: "5 saniyede Harry Potter'dan 3 karakter söyle ama Harry olmasın.", en: 'Name 3 Harry Potter characters, but not Harry.' },
  { id: 'medium_50', difficulty: 'medium', category: 'entertainment', tr: "5 saniyede Game of Thrones'tan 3 karakter söyle.", en: 'Name 3 Game of Thrones characters.' },
  { id: 'medium_51', difficulty: 'medium', category: 'entertainment', tr: "5 saniyede Friends'ten 3 karakter söyle.", en: 'Name 3 Friends characters.' },
  { id: 'medium_52', difficulty: 'medium', category: 'entertainment', tr: '5 saniyede uzayda geçen 3 film söyle.', en: 'Name 3 movies set in space.' },
  { id: 'medium_53', difficulty: 'medium', category: 'entertainment', tr: '5 saniyede zombi içeren 3 film veya dizi söyle.', en: 'Name 3 movies or shows with zombies.' },
  { id: 'medium_54', difficulty: 'medium', category: 'entertainment', tr: '5 saniyede bir video oyunundan uyarlanan 3 film veya dizi söyle.', en: 'Name 3 movies or shows adapted from a video game.' },
  { id: 'medium_55', difficulty: 'medium', category: 'entertainment', tr: '5 saniyede 3 film serisi söyle.', en: 'Name 3 movie franchises.' },
  { id: 'medium_56', difficulty: 'medium', category: 'music', tr: '5 saniyede İngiliz olmayan 3 ünlü şarkıcı söyle.', en: "Name 3 famous singers who aren't British." },
  { id: 'medium_57', difficulty: 'medium', category: 'music', tr: '5 saniyede 3 rapçi söyle ama hiçbiri Amerikalı olmasın.', en: 'Name 3 rappers, none of them American.' },
  { id: 'medium_58', difficulty: 'medium', category: 'music', tr: '5 saniyede 3 kadın rapçi söyle.', en: 'Name 3 female rappers.' },
  { id: 'medium_59', difficulty: 'medium', category: 'music', tr: '5 saniyede tek kelimelik sahne adı kullanan 3 sanatçı söyle.', en: 'Name 3 artists who go by a one-word stage name.' },
  { id: 'medium_60', difficulty: 'medium', category: 'music', tr: '5 saniyede İngiliz 3 şarkıcı söyle ama Adele olmasın.', en: 'Name 3 British singers, but not Adele.' },
  { id: 'medium_61', difficulty: 'medium', category: 'music', tr: "5 saniyede Kanadalı 3 şarkıcı söyle.", en: 'Name 3 Canadian singers.' },
  { id: 'medium_62', difficulty: 'medium', category: 'music', tr: '5 saniyede bir gruptan çıkıp solo kariyer yapan 3 şarkıcı söyle.', en: 'Name 3 singers who went solo after leaving a group.' },
  { id: 'medium_63', difficulty: 'medium', category: 'music', tr: "5 saniyede 2000'lerden 3 pop yıldızı söyle.", en: 'Name 3 pop stars from the 2000s.' },
  { id: 'medium_64', difficulty: 'medium', category: 'music', tr: '5 saniyede dansıyla ünlü 3 şarkıcı söyle.', en: 'Name 3 singers famous for their dancing.' },
  { id: 'medium_65', difficulty: 'medium', category: 'music', tr: '5 saniyede 3 erkek solo sanatçı söyle ama hiçbiri rapçi olmasın.', en: 'Name 3 male solo artists, none of them rappers.' },
  { id: 'medium_66', difficulty: 'medium', category: 'tech', tr: '5 saniyede 3 lüks otomobil markası söyle.', en: 'Name 3 luxury car brands.' },
  { id: 'medium_67', difficulty: 'medium', category: 'tech', tr: '5 saniyede Alman olmayan 3 otomobil markası söyle.', en: "Name 3 car brands that aren't German." },
  { id: 'medium_68', difficulty: 'medium', category: 'tech', tr: '5 saniyede 3 Japon otomobil markası söyle.', en: 'Name 3 Japanese car brands.' },
  { id: 'medium_69', difficulty: 'medium', category: 'tech', tr: '5 saniyede 3 İtalyan otomobil markası söyle.', en: 'Name 3 Italian car brands.' },
  { id: 'medium_70', difficulty: 'medium', category: 'tech', tr: '5 saniyede SUV üreten 3 lüks otomobil markası söyle.', en: 'Name 3 luxury car brands that make SUVs.' },
  { id: 'medium_71', difficulty: 'medium', category: 'tech', tr: '5 saniyede elektrikli otomobil üreten 3 marka söyle.', en: 'Name 3 brands that make electric cars.' },
  { id: 'medium_72', difficulty: 'medium', category: 'tech', tr: '5 saniyede logosunda hayvan bulunan 3 marka söyle.', en: 'Name 3 brands with an animal in their logo.' },
  { id: 'medium_73', difficulty: 'medium', category: 'tech', tr: '5 saniyede adı 5 harften uzun 3 teknoloji şirketi söyle.', en: 'Name 3 tech companies with names longer than 5 letters.' },
  { id: 'medium_74', difficulty: 'medium', category: 'tech', tr: '5 saniyede telefon üretmeyen 3 büyük teknoloji şirketi söyle.', en: "Name 3 big tech companies that don't make phones." },
  { id: 'medium_75', difficulty: 'medium', category: 'tech', tr: '5 saniyede 3 sosyal medya uygulaması söyle ama Instagram ve TikTok olmasın.', en: 'Name 3 social media apps, but not Instagram or TikTok.' },
  { id: 'medium_76', difficulty: 'medium', category: 'tech', tr: "5 saniyede 3 mesajlaşma uygulaması söyle ama WhatsApp olmasın.", en: "Name 3 messaging apps, but not WhatsApp." },
  { id: 'medium_77', difficulty: 'medium', category: 'tech', tr: '5 saniyede 3 streaming platformu söyle ama Netflix olmasın.', en: 'Name 3 streaming platforms, but not Netflix.' },
  { id: 'medium_78', difficulty: 'medium', category: 'tech', tr: "5 saniyede Google'a ait 3 uygulama veya servis söyle.", en: 'Name 3 apps or services owned by Google.' },
  { id: 'medium_79', difficulty: 'medium', category: 'tech', tr: "5 saniyede Meta'ya ait 3 uygulama veya platform söyle.", en: 'Name 3 apps or platforms owned by Meta.' },
  { id: 'medium_80', difficulty: 'medium', category: 'tech', tr: "5 saniyede Microsoft'a ait 3 ürün veya servis söyle.", en: 'Name 3 products or services owned by Microsoft.' },
  { id: 'medium_81', difficulty: 'medium', category: 'food', tr: '5 saniyede 3 Türk tatlısı söyle ama baklava olmasın.', en: 'Name 3 Turkish desserts, but not baklava.' },
  { id: 'medium_82', difficulty: 'medium', category: 'food', tr: '5 saniyede içinde et olmayan 3 Türk yemeği söyle.', en: 'Name 3 Turkish dishes without meat.' },
  { id: 'medium_83', difficulty: 'medium', category: 'food', tr: '5 saniyede kahvaltıda yenebilecek 3 sıcak yemek söyle.', en: 'Name 3 hot dishes you could eat for breakfast.' },
  { id: 'medium_84', difficulty: 'medium', category: 'food', tr: '5 saniyede kahve içermeyen 3 kafe içeceği söyle.', en: "Name 3 café drinks that don't contain coffee." },
  { id: 'medium_85', difficulty: 'medium', category: 'food', tr: '5 saniyede 3 kokteyl söyle ama Mojito olmasın.', en: 'Name 3 cocktails, but not Mojito.' },
  { id: 'medium_86', difficulty: 'medium', category: 'food', tr: '5 saniyede üç farklı ülkeden 3 yemek söyle.', en: 'Name 3 dishes from 3 different countries.' },
  { id: 'medium_87', difficulty: 'medium', category: 'food', tr: '5 saniyede kırmızı olmayan 3 meyve söyle.', en: "Name 3 fruits that aren't red." },
  { id: 'medium_88', difficulty: 'medium', category: 'food', tr: '5 saniyede pişirilmeden yenebilen 3 sebze söyle.', en: 'Name 3 vegetables you can eat without cooking.' },
  { id: 'medium_89', difficulty: 'medium', category: 'food', tr: '5 saniyede içinde peynir bulunan 3 yemek söyle.', en: 'Name 3 dishes that contain cheese.' },
  { id: 'medium_90', difficulty: 'medium', category: 'food', tr: '5 saniyede patates kullanılan 3 yemek söyle.', en: 'Name 3 dishes made with potatoes.' },
  { id: 'medium_91', difficulty: 'medium', category: 'food', tr: '5 saniyede İtalyan mutfağından 3 yemek söyle ama pizza olmasın.', en: 'Name 3 Italian dishes, but not pizza.' },
  { id: 'medium_92', difficulty: 'medium', category: 'food', tr: '5 saniyede Japon mutfağından 3 yemek söyle.', en: 'Name 3 Japanese dishes.' },
  { id: 'medium_93', difficulty: 'medium', category: 'food', tr: '5 saniyede Meksika mutfağından 3 yemek söyle.', en: 'Name 3 Mexican dishes.' },
  { id: 'medium_94', difficulty: 'medium', category: 'food', tr: '5 saniyede elle yenebilecek 3 yemek söyle.', en: 'Name 3 foods you can eat with your hands.' },
  { id: 'medium_95', difficulty: 'medium', category: 'food', tr: '5 saniyede şerbetli 3 tatlı söyle.', en: 'Name 3 syrup-soaked desserts.' },

  // ---------------------------------------------------------------------
  // SOCIAL / PARTY
  // ---------------------------------------------------------------------
  { id: 'social_1', difficulty: 'medium', category: 'social', tr: '5 saniyede bir arkadaşının senden saklayabileceği 3 şey söyle.', en: 'Name 3 things a friend might be hiding from you.' },
  { id: 'social_2', difficulty: 'medium', category: 'social', tr: '5 saniyede ilk buluşmada konuşulmaması gereken 3 konu söyle.', en: "Name 3 topics you shouldn't bring up on a first date." },
  { id: 'social_3', difficulty: 'medium', category: 'social', tr: '5 saniyede bir ilişkide red flag olabilecek 3 şey söyle.', en: 'Name 3 things that could be a red flag in a relationship.' },
  { id: 'social_4', difficulty: 'medium', category: 'social', tr: '5 saniyede bir ilişkide green flag olabilecek 3 şey söyle.', en: 'Name 3 things that could be a green flag in a relationship.' },
  { id: 'social_5', difficulty: 'medium', category: 'social', tr: '5 saniyede bir arkadaşını sinirlendirecek 3 şey söyle.', en: 'Name 3 things that would annoy a friend.' },
  { id: 'social_6', difficulty: 'medium', category: 'social', tr: "5 saniyede gece 3'te yazabileceğin 3 kişi tipi söyle.", en: 'Name 3 types of people you might text at 3 AM.' },
  { id: 'social_7', difficulty: 'medium', category: 'social', tr: '5 saniyede bir partiyi mahvedebilecek 3 şey söyle.', en: 'Name 3 things that could ruin a party.' },
  { id: 'social_8', difficulty: 'medium', category: 'social', tr: '5 saniyede grup chatinde kavga çıkarabilecek 3 şey söyle.', en: 'Name 3 things that could start a fight in a group chat.' },
  { id: 'social_9', difficulty: 'medium', category: 'social', tr: "5 saniyede date'ten erken ayrılmana sebep olacak 3 şey söyle.", en: 'Name 3 things that would make you leave a date early.' },
  { id: 'social_10', difficulty: 'medium', category: 'social', tr: "5 saniyede bir date'ten erken çıkmak için 3 bahane söyle.", en: 'Name 3 excuses to leave a date early.' },
  { id: 'social_11', difficulty: 'medium', category: 'social', tr: '5 saniyede mesaja geç cevap vermek için 3 bahane söyle.', en: 'Name 3 excuses for replying to a text late.' },
  { id: 'social_12', difficulty: 'medium', category: 'social', tr: '5 saniyede eski sevgiline yazmamak için 3 sebep söyle.', en: 'Name 3 reasons not to text your ex.' },
  { id: 'social_13', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin senden hoşlandığını düşündürecek 3 davranış söyle.', en: 'Name 3 behaviors that would make you think someone likes you.' },
  { id: 'social_14', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin seni ghostladığını düşündürecek 3 şey söyle.', en: 'Name 3 things that would make you think someone ghosted you.' },
  { id: 'social_15', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin kıskanç olduğunu düşündürecek 3 davranış söyle.', en: 'Name 3 behaviors that would make you think someone is jealous.' },
  { id: 'social_16', difficulty: 'medium', category: 'social', tr: '5 saniyede flörtöz birinin yapabileceği 3 şey söyle.', en: 'Name 3 things a flirty person might do.' },
  { id: 'social_17', difficulty: 'medium', category: 'social', tr: '5 saniyede bir arkadaşlığı bitirebilecek 3 şey söyle.', en: 'Name 3 things that could end a friendship.' },
  { id: 'social_18', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin güvenini kaybetmesine sebep olacak 3 şey söyle.', en: 'Name 3 things that would make someone lose your trust.' },
  { id: 'social_19', difficulty: 'medium', category: 'social', tr: '5 saniyede partiye davet etmek istemeyeceğin 3 kişi tipi söyle.', en: "Name 3 types of people you wouldn't want to invite to a party." },
  { id: 'social_20', difficulty: 'medium', category: 'social', tr: '5 saniyede tatilde arkadaş grubunu kavga ettirebilecek 3 şey söyle.', en: 'Name 3 things that could make a friend group fight on vacation.' },
  { id: 'social_21', difficulty: 'medium', category: 'social', tr: "5 saniyede gece 3'te yapmaman gereken 3 şey söyle.", en: 'Name 3 things you shouldn’t do at 3 AM.' },
  { id: 'social_22', difficulty: 'medium', category: 'social', tr: '5 saniyede yanlış kişiye göndermek istemeyeceğin 3 mesaj türü söyle.', en: "Name 3 types of messages you wouldn't want to send to the wrong person." },
  { id: 'social_23', difficulty: 'medium', category: 'social', tr: '5 saniyede telefonunda birinin görmesini istemeyeceğin 3 şey söyle.', en: "Name 3 things on your phone you wouldn't want someone to see." },
  { id: 'social_24', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin egoist olduğunu düşündürecek 3 davranış söyle.', en: 'Name 3 behaviors that would make you think someone is selfish.' },
  { id: 'social_25', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin yalan söylediğini düşündürecek 3 davranış söyle.', en: 'Name 3 behaviors that would make you think someone is lying.' },
  { id: 'social_26', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin zengin olduğunu düşündürecek 3 şey söyle.', en: 'Name 3 things that would make you think someone is rich.' },
  { id: 'social_27', difficulty: 'medium', category: 'social', tr: '5 saniyede influencer olduğunu düşündürecek 3 şey söyle.', en: 'Name 3 things that would make you think someone is an influencer.' },
  { id: 'social_28', difficulty: 'medium', category: 'social', tr: '5 saniyede ilk buluşmada iyi izlenim bırakacak 3 şey söyle.', en: 'Name 3 things that would make a good impression on a first date.' },
  { id: 'social_29', difficulty: 'medium', category: 'social', tr: '5 saniyede sevgilinin telefonunda görmek istemeyeceğin 3 şey söyle.', en: "Name 3 things you wouldn't want to see on your partner's phone." },
  { id: 'social_30', difficulty: 'medium', category: 'social', tr: '5 saniyede arkadaş grubunda en çok tartışılan 3 konu söyle.', en: 'Name 3 topics that get argued about most in a friend group.' },
  { id: 'social_31', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin senden özür dilemesini gerektirecek 3 şey söyle.', en: 'Name 3 things that would require someone to apologize to you.' },
  { id: 'social_32', difficulty: 'medium', category: 'social', tr: '5 saniyede bir partide yapılabilecek 3 utanç verici şey söyle.', en: 'Name 3 embarrassing things that could happen at a party.' },
  { id: 'social_33', difficulty: 'medium', category: 'social', tr: '5 saniyede bir arkadaşına asla söylememen gereken 3 şey söyle.', en: 'Name 3 things you should never say to a friend.' },
  { id: 'social_34', difficulty: 'medium', category: 'social', tr: "5 saniyede ilk date'te yapılmaması gereken 3 şey söyle.", en: "Name 3 things you shouldn't do on a first date." },
  { id: 'social_35', difficulty: 'medium', category: 'social', tr: '5 saniyede birinin seni stalkladığını düşündürecek 3 şey söyle.', en: 'Name 3 things that would make you think someone is stalking you.' },

  // ---------------------------------------------------------------------
  // HARD
  // ---------------------------------------------------------------------
  { id: 'hard_1', difficulty: 'hard', category: 'geography', tr: '5 saniyede iki kıtada toprağı olan 3 ülke söyle.', en: 'Name 3 countries with land on two continents.' },
  { id: 'hard_2', difficulty: 'hard', category: 'geography', tr: "5 saniyede Avrupa'da euro kullanmayan 3 AB ülkesi söyle.", en: "Name 3 EU countries that don't use the euro." },
  { id: 'hard_3', difficulty: 'hard', category: 'geography', tr: '5 saniyede monarşiyle yönetilen 3 Avrupa ülkesi söyle.', en: 'Name 3 European countries ruled by a monarchy.' },
  { id: 'hard_4', difficulty: 'hard', category: 'geography', tr: '5 saniyede birden fazla resmi dili bulunan 3 ülke söyle.', en: 'Name 3 countries with more than one official language.' },
  { id: 'hard_5', difficulty: 'hard', category: 'geography', tr: '5 saniyede sol taraftan trafik akan 3 ülke söyle.', en: 'Name 3 countries that drive on the left.' },
  { id: 'hard_6', difficulty: 'hard', category: 'geography', tr: '5 saniyede içinde A harfi olmayan 3 ülke adı söyle.', en: 'Name 3 country names without the letter A.' },
  { id: 'hard_7', difficulty: 'hard', category: 'geography', tr: '5 saniyede içinde E harfi olmayan 3 ülke adı söyle.', en: 'Name 3 country names without the letter E.' },
  { id: 'hard_8', difficulty: 'hard', category: 'geography', tr: '5 saniyede adı 7 harften uzun 3 ülke söyle.', en: 'Name 3 countries with names longer than 7 letters.' },
  { id: 'hard_9', difficulty: 'hard', category: 'sports', tr: '5 saniyede Dünya Kupası kazanmış 3 Güney Amerikalı futbolcu söyle.', en: 'Name 3 South American World Cup-winning footballers.' },
  { id: 'hard_10', difficulty: 'hard', category: 'sports', tr: "5 saniyede Premier League'de oynamış 3 Fransız forvet söyle.", en: 'Name 3 French forwards who have played in the Premier League.' },
  { id: 'hard_11', difficulty: 'hard', category: 'sports', tr: "5 saniyede Real Madrid ve Premier League'de oynamış 3 futbolcu söyle.", en: 'Name 3 footballers who have played for Real Madrid and in the Premier League.' },
  { id: 'hard_12', difficulty: 'hard', category: 'sports', tr: "5 saniyede Barcelona ve Premier League'de oynamış 3 futbolcu söyle.", en: 'Name 3 footballers who have played for Barcelona and in the Premier League.' },
  { id: 'hard_13', difficulty: 'hard', category: 'sports', tr: '5 saniyede İspanyol olmayan 3 La Liga gol kralı söyle.', en: 'Name 3 non-Spanish La Liga top scorers.' },
  { id: 'hard_14', difficulty: 'hard', category: 'sports', tr: "5 saniyede Ballon d'Or kazanmış 3 Real Madrid futbolcusu söyle.", en: 'Name 3 Ballon d’Or-winning Real Madrid players.' },
  { id: 'hard_15', difficulty: 'hard', category: 'sports', tr: "5 saniyede Şampiyonlar Ligi'ni iki farklı kulüple kazanmış 3 futbolcu söyle.", en: 'Name 3 footballers who have won the Champions League with two different clubs.' },
  { id: 'hard_16', difficulty: 'hard', category: 'entertainment', tr: '5 saniyede Oscar kazanmış 3 yönetmen söyle.', en: 'Name 3 Oscar-winning directors.' },
  { id: 'hard_17', difficulty: 'hard', category: 'entertainment', tr: '5 saniyede Christopher Nolan filminde oynamış 3 Oscar ödüllü oyuncu söyle.', en: 'Name 3 Oscar-winning actors who have appeared in a Christopher Nolan film.' },
  { id: 'hard_18', difficulty: 'hard', category: 'entertainment', tr: "5 saniyede Leonardo DiCaprio ve Martin Scorsese'nin birlikte yaptığı 3 film söyle.", en: 'Name 3 films Leonardo DiCaprio and Martin Scorsese made together.' },
  { id: 'hard_19', difficulty: 'hard', category: 'entertainment', tr: "5 saniyede 2000'den önce Oscar En İyi Film kazanmış 3 film söyle.", en: 'Name 3 Best Picture Oscar winners from before 2000.' },
  { id: 'hard_20', difficulty: 'hard', category: 'entertainment', tr: '5 saniyede birden fazla süper kahraman filmi serisinde oynamış 3 oyuncu söyle.', en: 'Name 3 actors who have appeared in more than one superhero film franchise.' },

  // ---------------------------------------------------------------------
  // CHAOS
  // ---------------------------------------------------------------------
  { id: 'chaos_1', difficulty: 'chaos', category: 'geography', tr: "5 saniyede 3 ülke söyle ama Avrupa'dan olmasın.", en: 'Name 3 countries, but none from Europe.' },
  { id: 'chaos_2', difficulty: 'chaos', category: 'sports', tr: "5 saniyede 3 futbolcu söyle ama Messi, Ronaldo ve Mbappé olmasın.", en: 'Name 3 footballers, but not Messi, Ronaldo, or Mbappé.' },
  { id: 'chaos_3', difficulty: 'chaos', category: 'sports', tr: "5 saniyede 3 Premier League takımı söyle ama Londra'dan olmasın.", en: 'Name 3 Premier League teams, but none from London.' },
  { id: 'chaos_4', difficulty: 'chaos', category: 'entertainment', tr: '5 saniyede 3 film söyle ama hiçbirinde Leonardo DiCaprio oynamasın.', en: 'Name 3 movies, but none starring Leonardo DiCaprio.' },
  { id: 'chaos_5', difficulty: 'chaos', category: 'tech', tr: "5 saniyede 3 sosyal medya uygulaması söyle ama Meta'ya ait olmasın.", en: 'Name 3 social media apps, but none owned by Meta.' },
  { id: 'chaos_6', difficulty: 'chaos', category: 'tech', tr: '5 saniyede 3 otomobil markası söyle ama Alman olmasın.', en: 'Name 3 car brands, but none German.' },
  { id: 'chaos_7', difficulty: 'chaos', category: 'food', tr: '5 saniyede 3 Türk yemeği söyle ama içinde et olmasın.', en: 'Name 3 Turkish dishes, but none with meat.' },
  { id: 'chaos_8', difficulty: 'chaos', category: 'food', tr: '5 saniyede 3 meyve söyle ama kırmızı olmasın.', en: 'Name 3 fruits, but none red.' },
  { id: 'chaos_9', difficulty: 'chaos', category: 'music', tr: '5 saniyede 3 şarkıcı söyle ama Amerikalı olmasın.', en: 'Name 3 singers, but none American.' },
  { id: 'chaos_10', difficulty: 'chaos', category: 'geography', tr: '5 saniyede 3 Avrupa şehri söyle ama başkent olmasın.', en: 'Name 3 European cities, but none capitals.' },
  { id: 'chaos_11', difficulty: 'chaos', category: 'sports', tr: '5 saniyede 3 futbol takımı söyle ama İngiliz olmasın.', en: 'Name 3 football teams, but none English.' },
  { id: 'chaos_12', difficulty: 'chaos', category: 'food', tr: '5 saniyede 3 tatlı söyle ama çikolata içermesin.', en: 'Name 3 desserts, but none containing chocolate.' },
  { id: 'chaos_13', difficulty: 'chaos', category: 'tech', tr: '5 saniyede 3 mesajlaşma uygulaması söyle ama WhatsApp ve Messenger olmasın.', en: 'Name 3 messaging apps, but not WhatsApp or Messenger.' },
  { id: 'chaos_14', difficulty: 'chaos', category: 'social', tr: "5 saniyede 3 date fikri söyle ama restoran olmasın.", en: 'Name 3 date ideas, but none involving a restaurant.' },
  { id: 'chaos_15', difficulty: 'chaos', category: 'social', tr: '5 saniyede 3 hafta sonu aktivitesi söyle ama evden çıkman gereksin.', en: 'Name 3 weekend activities that require leaving the house.' },
  { id: 'chaos_16', difficulty: 'chaos', category: 'sports', tr: '5 saniyede 3 spor söyle ama top kullanılmasın.', en: 'Name 3 sports, but none using a ball.' },
  { id: 'chaos_17', difficulty: 'chaos', category: 'tech', tr: '5 saniyede 3 lüks marka söyle ama otomobil markası olmasın.', en: 'Name 3 luxury brands, but none car brands.' },
  { id: 'chaos_18', difficulty: 'chaos', category: 'geography', tr: '5 saniyede 3 ülke söyle ama adında A harfi olmasın.', en: 'Name 3 countries, but none with the letter A in their name.' },
  { id: 'chaos_19', difficulty: 'chaos', category: 'entertainment', tr: '5 saniyede 3 film karakteri söyle ama süper kahraman olmasın.', en: 'Name 3 movie characters, but none superheroes.' },
  { id: 'chaos_20', difficulty: 'chaos', category: 'tech', tr: '5 saniyede 3 uygulama söyle ama sosyal medya uygulaması olmasın.', en: 'Name 3 apps, but none social media apps.' },
];

export const getChallengesByFilter = (difficulty?: FiveSecondDifficulty, category?: FiveSecondCategory) =>
  FIVE_SECOND_CHALLENGES.filter((c) => (!difficulty || c.difficulty === difficulty) && (!category || c.category === category));

export const getRandomFiveSecondChallenge = (difficulty?: FiveSecondDifficulty, category?: FiveSecondCategory, excludeIds: string[] = []) => {
  const pool = FIVE_SECOND_CHALLENGES.filter((c) => (!difficulty || c.difficulty === difficulty) && (!category || c.category === category) && !excludeIds.includes(c.id));
  return pool.length ? pool[Math.floor(Math.random() * pool.length)] : null;
};
