export type ExposeMeCategory = 'stalking' | 'flirty' | 'messages' | 'funny' | 'savage' | 'confession' | 'quick';
export type ExposeMeIntensity = 'soft' | 'balanced' | 'bold';

export type ExposeMeQuestion = {
  id: string;
  category: ExposeMeCategory;
  intensity: ExposeMeIntensity;
  tr: string;
  en: string;
};

export const EXPOSE_ME_QUESTIONS: ExposeMeQuestion[] = [
  { id: 'exp_1', category: 'stalking', intensity: 'balanced', tr: 'En son kimin profilini stalkladın?', en: "Who's the last person whose profile you stalked?" },
  { id: 'exp_2', category: 'stalking', intensity: 'balanced', tr: 'En son kimin Instagram hikâyesine gizlice baktın?', en: "Who's the last person whose Instagram story you secretly watched?" },
  { id: 'exp_3', category: 'stalking', intensity: 'soft', tr: "En son kimi Google'da arattın?", en: "Who's the last person you Googled?" },
  { id: 'exp_4', category: 'stalking', intensity: 'balanced', tr: 'En son kimin eski fotoğraflarına kadar indin?', en: "Who's the last person whose old photos you scrolled all the way down to?" },
  { id: 'exp_5', category: 'stalking', intensity: 'soft', tr: 'En son kimin takipçilerini kontrol ettin?', en: "Who's the last person whose followers you checked?" },
  { id: 'exp_6', category: 'stalking', intensity: 'soft', tr: 'En son kimin beğenilerini inceledin?', en: "Who's the last person whose likes you looked through?" },
  { id: 'exp_7', category: 'stalking', intensity: 'bold', tr: 'En son kimin eski sevgilisini stalkladın?', en: "Who's the last person whose ex you stalked?" },
  { id: 'exp_8', category: 'stalking', intensity: 'balanced', tr: 'En son kimin seni takip edip etmediğini kontrol ettin?', en: "Who's the last person you checked to see if they follow you?" },
  { id: 'exp_9', category: 'stalking', intensity: 'soft', tr: 'En son kimin profil fotoğrafını büyüttün?', en: "Whose profile picture did you last zoom in on?" },
  { id: 'exp_10', category: 'stalking', intensity: 'soft', tr: 'En son kimin hakkında arkadaşına "şuna bir baksana" dedin?', en: "Who's the last person you told a friend to \"check this out\" about?" },
  { id: 'exp_11', category: 'flirty', intensity: 'balanced', tr: "Şu an bir crush'ın var mı?", en: 'Do you have a crush right now?' },
  { id: 'exp_12', category: 'flirty', intensity: 'balanced', tr: 'Bu odadaki biriyle date\'e çıkar mıydın?', en: 'Would you go on a date with someone in this room?' },
  { id: 'exp_13', category: 'flirty', intensity: 'balanced', tr: 'Bu odadaki en çekici kişi kim?', en: "Who's the most attractive person in this room?" },
  { id: 'exp_14', category: 'flirty', intensity: 'balanced', tr: 'Bu odadaki biri sana yazsa en çok kimin yazmasını isterdin?', en: 'If someone in this room texted you, who would you most want it to be?' },
  { id: 'exp_15', category: 'flirty', intensity: 'soft', tr: 'En son kime ilk mesajı sen attın?', en: "Who's the last person you texted first?" },
  { id: 'exp_16', category: 'flirty', intensity: 'soft', tr: 'En son kimden mesaj bekledin?', en: "Who's the last person you waited for a text from?" },
  { id: 'exp_17', category: 'flirty', intensity: 'balanced', tr: 'En son kim seni heyecanlandırdı?', en: "Who's the last person who gave you butterflies?" },
  { id: 'exp_18', category: 'flirty', intensity: 'soft', tr: 'En son kimin mesajını görünce hemen cevap verdin?', en: "Whose text did you last reply to instantly?" },
  { id: 'exp_19', category: 'flirty', intensity: 'soft', tr: 'En son kimin mesajına bilerek geç cevap verdin?', en: "Whose text did you last reply to late on purpose?" },
  { id: 'exp_20', category: 'flirty', intensity: 'balanced', tr: 'Hiç hoşlandığın kişiye bilerek story attın mı?', en: 'Have you ever posted a story on purpose for someone you liked to see?' },
  { id: 'exp_21', category: 'flirty', intensity: 'balanced', tr: "Hiç birinin dikkatini çekmek için story paylaştın mı?", en: "Have you ever posted a story just to get someone's attention?" },
  { id: 'exp_22', category: 'savage', intensity: 'bold', tr: 'Hiç birini kıskandırmak için fotoğraf paylaştın mı?', en: 'Have you ever posted a photo to make someone jealous?' },
  { id: 'exp_23', category: 'flirty', intensity: 'balanced', tr: "Hiç crush'ının story'sini birden fazla kez izledin mi?", en: "Have you ever watched your crush's story more than once?" },
  { id: 'exp_24', category: 'stalking', intensity: 'soft', tr: 'Hiç birinin online olup olmadığını kontrol ettin mi?', en: 'Have you ever checked if someone was online?' },
  { id: 'exp_25', category: 'funny', intensity: 'soft', tr: 'Hiç "yanlışlıkla" birinin eski fotoğrafını beğendin mi?', en: 'Have you ever "accidentally" liked someone\'s old photo?' },
  { id: 'exp_26', category: 'flirty', intensity: 'soft', tr: 'En son kim sana "acaba benden hoşlanıyor mu?" dedirtti?', en: 'Who\'s the last person who made you think "do they like me?"' },
  { id: 'exp_27', category: 'savage', intensity: 'bold', tr: 'Hiç arkadaşının hoşlandığı birinden hoşlandın mı?', en: 'Have you ever liked someone your friend liked?' },
  { id: 'exp_28', category: 'confession', intensity: 'balanced', tr: 'Hiç eski sevgiline geri dönmeyi düşündün mü?', en: 'Have you ever thought about getting back with an ex?' },
  { id: 'exp_29', category: 'confession', intensity: 'balanced', tr: 'Eski sevgililerinden biri sana yazsa cevap verir misin?', en: 'If one of your exes texted you, would you reply?' },
  { id: 'exp_30', category: 'confession', intensity: 'balanced', tr: 'Şu an eski sevgililerinden birini merak ediyor musun?', en: 'Are you currently wondering about one of your exes?' },
  { id: 'exp_31', category: 'flirty', intensity: 'balanced', tr: "Hiç arkadaşına crush'ının ekran görüntüsünü attın mı?", en: "Have you ever sent a friend a screenshot of your crush?" },
  { id: 'exp_32', category: 'funny', intensity: 'soft', tr: 'En son kimin fotoğrafını arkadaş grubuna attın?', en: "Whose photo did you last send to your friend group chat?" },
  { id: 'exp_33', category: 'stalking', intensity: 'soft', tr: 'Hiç birinin fotoğrafını yakınlaştırıp inceledin mi?', en: "Have you ever zoomed in on someone's photo to inspect it?" },
  { id: 'exp_34', category: 'flirty', intensity: 'balanced', tr: 'Hiç hoşlandığın birinin arkadaşlarıyla yakınlaşmaya çalıştın mı?', en: "Have you ever tried to get closer to your crush's friends?" },
  { id: 'exp_35', category: 'confession', intensity: 'balanced', tr: 'Birinden hoşlanıp ona hiç söylemediğin oldu mu?', en: 'Have you ever liked someone and never told them?' },
  { id: 'exp_36', category: 'stalking', intensity: 'soft', tr: "Instagram'da en çok kimi kontrol ediyorsun?", en: 'Who do you check on Instagram the most?' },
  { id: 'exp_37', category: 'savage', intensity: 'balanced', tr: 'En son kimi unfollow etmeyi düşündün?', en: "Who's the last person you thought about unfollowing?" },
  { id: 'exp_38', category: 'savage', intensity: 'balanced', tr: "En son kimi mute'ladın?", en: "Who's the last person you muted?" },
  { id: 'exp_39', category: 'savage', intensity: 'balanced', tr: "En son kimi close friends'ten çıkardın?", en: "Who's the last person you removed from close friends?" },
  { id: 'exp_40', category: 'funny', intensity: 'soft', tr: 'Hiç birini takipten çıkarıp geri takip ettin mi?', en: 'Have you ever unfollowed someone and then followed them back?' },
  { id: 'exp_41', category: 'stalking', intensity: 'bold', tr: 'Hiç fake hesaptan birine baktın mı?', en: 'Have you ever looked at someone from a fake account?' },
  { id: 'exp_42', category: 'stalking', intensity: 'bold', tr: 'Hiç ikinci hesabından birini stalkladın mı?', en: 'Have you ever stalked someone from a second account?' },
  { id: 'exp_43', category: 'stalking', intensity: 'soft', tr: "En son kimin TikTok repostlarına baktın?", en: "Whose TikTok reposts did you last look at?" },
  { id: 'exp_44', category: 'stalking', intensity: 'soft', tr: 'En son kimin Spotify hesabına baktın?', en: "Whose Spotify account did you last check?" },
  { id: 'exp_45', category: 'stalking', intensity: 'balanced', tr: 'Hiç birinin takip ettiği yeni kişileri kontrol ettin mi?', en: 'Have you ever checked the new people someone started following?' },
  { id: 'exp_46', category: 'stalking', intensity: 'soft', tr: "Hiç birinin follower sayısının değiştiğini fark ettin mi?", en: "Have you ever noticed someone's follower count change?" },
  { id: 'exp_47', category: 'savage', intensity: 'bold', tr: 'Hiç eski sevgilinin yeni sevgilisini stalkladın mı?', en: "Have you ever stalked your ex's new partner?" },
  { id: 'exp_48', category: 'savage', intensity: 'bold', tr: 'Hiç arkadaşının eski sevgilisini stalkladın mı?', en: "Have you ever stalked your friend's ex?" },
  { id: 'exp_49', category: 'funny', intensity: 'soft', tr: 'En son kimin profilini arkadaşına gönderdin?', en: "Whose profile did you last send to a friend?" },
  { id: 'exp_50', category: 'funny', intensity: 'soft', tr: 'Telefonunda en çok ekran görüntüsü aldığın şey ne?', en: 'What do you screenshot the most on your phone?' },
  { id: 'exp_51', category: 'funny', intensity: 'balanced', tr: 'Galerinde açıklaması zor bir screenshot var mı?', en: "Do you have a screenshot in your gallery that's hard to explain?" },
  { id: 'exp_52', category: 'messages', intensity: 'soft', tr: "En son hangi mesajın screenshot'ını aldın?", en: "What's the last message you screenshotted?" },
  { id: 'exp_53', category: 'messages', intensity: 'balanced', tr: 'Hiç bir mesajı arkadaş grubuna göndermek için screenshot aldın mı?', en: 'Have you ever screenshotted a message to send to your friend group?' },
  { id: 'exp_54', category: 'stalking', intensity: 'balanced', tr: "Hiç birinin story'sini ekran görüntüsü aldın mı?", en: "Have you ever screenshotted someone's story?" },
  { id: 'exp_55', category: 'stalking', intensity: 'balanced', tr: 'En son hangi hesabı gizlice kontrol ettin?', en: "What's the last account you secretly checked?" },
  { id: 'exp_56', category: 'messages', intensity: 'balanced', tr: 'En son kimi ghostladın?', en: "Who's the last person you ghosted?" },
  { id: 'exp_57', category: 'messages', intensity: 'balanced', tr: 'En son kim seni ghostladı?', en: "Who's the last person who ghosted you?" },
  { id: 'exp_58', category: 'messages', intensity: 'soft', tr: 'En uzun ne kadar süre bir mesaja bilerek cevap vermedin?', en: "What's the longest you've ever left someone on read on purpose?" },
  { id: 'exp_59', category: 'messages', intensity: 'soft', tr: 'Hiç mesajı okuyup "görmedim" dedin mi?', en: 'Have you ever read a message and said you didn\'t see it?' },
  { id: 'exp_60', category: 'funny', intensity: 'soft', tr: 'Hiç "uyuyordum" deyip aslında online olduğun oldu mu?', en: 'Have you ever said "I was asleep" when you were actually online?' },
  { id: 'exp_61', category: 'funny', intensity: 'soft', tr: 'Hiç "telefonum elimde değildi" diye yalan söyledin mi?', en: 'Have you ever lied and said "my phone wasn\'t on me"?' },
  { id: 'exp_62', category: 'messages', intensity: 'soft', tr: 'En son hangi bahaneyle mesajdan kaçtın?', en: "What's the last excuse you used to dodge a text?" },
  { id: 'exp_63', category: 'funny', intensity: 'soft', tr: 'Hiç bir mesajı arkadaşlarına gösterip birlikte cevap yazdınız mı?', en: 'Have you ever shown a message to your friends and written the reply together?' },
  { id: 'exp_64', category: 'messages', intensity: 'soft', tr: 'Hiç gönderdiğin mesajı anında silmek istediğin oldu mu?', en: 'Have you ever wanted to instantly delete a message right after sending it?' },
  { id: 'exp_65', category: 'messages', intensity: 'balanced', tr: 'En son kime mesaj atıp pişman oldun?', en: "Who's the last person you texted and regretted it?" },
  { id: 'exp_66', category: 'savage', intensity: 'bold', tr: 'Hiç sarhoşken birine mesaj attın mı?', en: 'Have you ever texted someone while drunk?' },
  { id: 'exp_67', category: 'confession', intensity: 'bold', tr: 'Hiç eski sevgiline gece mesaj attın mı?', en: 'Have you ever texted your ex late at night?' },
  { id: 'exp_68', category: 'funny', intensity: 'soft', tr: 'Hiç birine yanlışlıkla başka biri hakkında mesaj gönderdin mi?', en: 'Have you ever accidentally sent someone a message about someone else?' },
  { id: 'exp_69', category: 'funny', intensity: 'soft', tr: 'Hiç "haha" yazıp aslında hiç gülmedin mi?', en: 'Have you ever typed "haha" without actually laughing?' },
  { id: 'exp_70', category: 'funny', intensity: 'soft', tr: 'Hiç konuşmayı bitirmek için "uyuyacağım" dedin mi?', en: 'Have you ever said "I\'m going to sleep" just to end a conversation?' },
  { id: 'exp_71', category: 'confession', intensity: 'balanced', tr: 'En son söylediğin küçük yalan neydi?', en: "What's the last small lie you told?" },
  { id: 'exp_72', category: 'confession', intensity: 'balanced', tr: 'En son ne hakkında yalan söyledin?', en: "What's the last thing you lied about?" },
  { id: 'exp_73', category: 'funny', intensity: 'soft', tr: 'Hiç birini tanımıyormuş gibi yaptın mı?', en: "Have you ever pretended not to know someone?" },
  { id: 'exp_74', category: 'funny', intensity: 'soft', tr: 'Hiç birinden kaçmak için yolunu değiştirdin mi?', en: 'Have you ever changed your route to avoid someone?' },
  { id: 'exp_75', category: 'funny', intensity: 'soft', tr: 'Hiç biriyle karşılaşmamak için mekândan çıktın mı?', en: 'Have you ever left a place to avoid running into someone?' },
  { id: 'exp_76', category: 'messages', intensity: 'soft', tr: 'Hiç yanlış kişiye mesaj attın mı?', en: 'Have you ever texted the wrong person?' },
  { id: 'exp_77', category: 'messages', intensity: 'balanced', tr: 'Hiç yanlış kişiye fotoğraf gönderdin mi?', en: 'Have you ever sent a photo to the wrong person?' },
  { id: 'exp_78', category: 'confession', intensity: 'balanced', tr: "En son neyi Google'da aratmaya utandın?", en: "What's the last thing you were embarrassed to Google?" },
  { id: 'exp_79', category: 'confession', intensity: 'balanced', tr: 'En son neyi yaparken yakalanmak istemezdin?', en: "What's the last thing you wouldn't want to get caught doing?" },
  { id: 'exp_80', category: 'funny', intensity: 'soft', tr: 'Telefonunun arama geçmişindeki en garip şey ne?', en: "What's the weirdest thing in your phone's search history?" },
  { id: 'exp_81', category: 'funny', intensity: 'soft', tr: 'En utanç verici autocomplete önerin ne olabilir?', en: "What's your most embarrassing autocomplete suggestion?" },
  { id: 'exp_82', category: 'funny', intensity: 'soft', tr: "Hiç kendi adını Google'da arattın mı?", en: 'Have you ever Googled your own name?' },
  { id: 'exp_83', category: 'funny', intensity: 'soft', tr: 'Hiç kendi Instagram profilini başka hesaptan kontrol ettin mi?', en: 'Have you ever checked your own Instagram from another account?' },
  { id: 'exp_84', category: 'funny', intensity: 'soft', tr: "Hiç kendi story'ni kimlerin izlediğini defalarca kontrol ettin mi?", en: 'Have you ever checked who watched your story over and over?' },
  { id: 'exp_85', category: 'funny', intensity: 'soft', tr: 'Hiç attığın post yeterince like almadığı için sildin mi?', en: "Have you ever deleted a post because it didn't get enough likes?" },
  { id: 'exp_86', category: 'funny', intensity: 'soft', tr: "Hiç bir fotoğrafı paylaşmadan önce 20'den fazla kez çektin mi?", en: 'Have you ever taken more than 20 photos before posting one?' },
  { id: 'exp_87', category: 'flirty', intensity: 'balanced', tr: 'Hiç "tesadüfen oradaymışsın" gibi davranıp aslında bilerek gittin mi?', en: 'Have you ever acted like you "happened to be there" when you actually went on purpose?' },
  { id: 'exp_88', category: 'flirty', intensity: 'balanced', tr: 'Hiç birinin seni görmesi için belirli bir yere gittin mi?', en: 'Have you ever gone somewhere specifically so someone would see you?' },
  { id: 'exp_89', category: 'funny', intensity: 'soft', tr: 'Hiç arkadaşına "beni ara, buradan çıkmam lazım" dedin mi?', en: 'Have you ever told a friend "call me, I need to get out of here"?' },
  { id: 'exp_90', category: 'funny', intensity: 'soft', tr: "Hiç kötü bir date'ten kaçmak için bahane uydurdun mu?", en: 'Have you ever made up an excuse to escape a bad date?' },
  { id: 'exp_91', category: 'quick', intensity: 'bold', tr: 'Bu odada en az kime sır verirdin?', en: 'Who in this room would you trust with a secret the least?' },
  { id: 'exp_92', category: 'quick', intensity: 'bold', tr: 'Bu odada en çok kimin mesajını görmezden gelirsin?', en: 'Who in this room do you ignore messages from the most?' },
  { id: 'exp_93', category: 'quick', intensity: 'bold', tr: 'Bu odada en çok kim drama çıkarır?', en: 'Who in this room causes the most drama?' },
  { id: 'exp_94', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim stalk yapıyordur?', en: 'Who in this room stalks people the most?' },
  { id: 'exp_95', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim eski sevgilisine geri döner?', en: 'Who in this room is most likely to get back with an ex?' },
  { id: 'exp_96', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim ghostlar?', en: 'Who in this room ghosts people the most?' },
  { id: 'exp_97', category: 'quick', intensity: 'bold', tr: 'Bu odada en çok kim "ben kıskanç değilim" deyip kıskançtır?', en: 'Who in this room says "I\'m not jealous" but actually is?' },
  { id: 'exp_98', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim flörtöz?', en: 'Who in this room is the flirtiest?' },
  { id: 'exp_99', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim mesajlara oyun oynar gibi cevap verir?', en: 'Who in this room plays games with texts the most?' },
  { id: 'exp_100', category: 'quick', intensity: 'bold', tr: 'Bu odada en çok kim gizli crush saklıyor?', en: 'Who in this room is hiding a secret crush?' },
  { id: 'exp_101', category: 'quick', intensity: 'bold', tr: 'Bu odada en çok kim toxic ilişkiye geri döner?', en: 'Who in this room goes back to toxic relationships the most?' },
  { id: 'exp_102', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim yanlış kişiye aşık olur?', en: 'Who in this room falls for the wrong person the most?' },
  { id: 'exp_103', category: 'quick', intensity: 'balanced', tr: "Bu odada en çok kim ilk date'te red flag verir?", en: 'Who in this room gives red flags on the first date the most?' },
  { id: 'exp_104', category: 'quick', intensity: 'bold', tr: 'Bu odada en çok kim birini kıskandırmaya çalışır?', en: 'Who in this room tries to make people jealous the most?' },
  { id: 'exp_105', category: 'quick', intensity: 'bold', tr: 'Bu odada en çok kim gizlice insanları stalklar?', en: 'Who in this room secretly stalks people the most?' },
  { id: 'exp_106', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim "umurumda değil" deyip aslında umursar?', en: 'Who in this room says "I don\'t care" but actually does?' },
  { id: 'exp_107', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim eski mesajları tekrar okur?', en: 'Who in this room rereads old messages the most?' },
  { id: 'exp_108', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim birinin online durumunu kontrol eder?', en: "Who in this room checks someone's online status the most?" },
  { id: 'exp_109', category: 'quick', intensity: 'balanced', tr: 'Bu odada en çok kim fake hesap açabilir?', en: 'Who in this room is most likely to make a fake account?' },
  { id: 'exp_110', category: 'quick', intensity: 'balanced', tr: "Bu odada en çok kim crush'ına ilk mesajı atar?", en: 'Who in this room is most likely to text their crush first?' },
  { id: 'exp_111', category: 'confession', intensity: 'balanced', tr: 'Kimsenin bilmediği küçük bir takıntın ne?', en: "What's a small obsession nobody knows about you?" },
  { id: 'exp_112', category: 'confession', intensity: 'balanced', tr: 'Son zamanlarda en çok kimi düşündün?', en: 'Who have you thought about the most lately?' },
  { id: 'exp_113', category: 'confession', intensity: 'balanced', tr: 'Şu an mesaj atmak isteyip atmadığın biri var mı?', en: "Is there someone you want to text right now but haven't?" },
  { id: 'exp_114', category: 'confession', intensity: 'balanced', tr: 'Unutamadığın biri var mı?', en: "Is there someone you can't forget?" },
  { id: 'exp_115', category: 'confession', intensity: 'balanced', tr: 'Sana geri yazmasını istediğin biri var mı?', en: 'Is there someone you wish would text you back?' },
  { id: 'exp_116', category: 'confession', intensity: 'soft', tr: 'En son kimi kıskandın?', en: "Who's the last person you were jealous of?" },
  { id: 'exp_117', category: 'confession', intensity: 'soft', tr: 'En son kimin hayatına özendin?', en: "Whose life did you last envy?" },
  { id: 'exp_118', category: 'confession', intensity: 'balanced', tr: 'En son kimi özledin ama söylemedin?', en: "Who's the last person you missed but didn't say?" },
  { id: 'exp_119', category: 'confession', intensity: 'soft', tr: 'En son kime sinirlendin ama belli etmedin?', en: "Who's the last person you were mad at but didn't show it?" },
  { id: 'exp_120', category: 'confession', intensity: 'balanced', tr: 'Hiç hâlâ hoşlandığın halde "umurumda değil" dedin mi?', en: 'Have you ever said "I don\'t care" while still liking someone?' },
  { id: 'exp_121', category: 'savage', intensity: 'bold', tr: 'Şu an biri telefonunu alsa en çok hangi uygulamayı açmasından korkarsın?', en: "If someone grabbed your phone right now, which app would you be most scared they'd open?" },
  { id: 'exp_122', category: 'savage', intensity: 'bold', tr: 'Telefonunda silmen gereken bir şey var mı?', en: 'Is there something on your phone you should delete?' },
  { id: 'exp_123', category: 'messages', intensity: 'soft', tr: "Şu anda DM'lerinde cevaplamadığın kaç kişi var?", en: "How many people are you currently not replying to in DMs?" },
  { id: 'exp_124', category: 'confession', intensity: 'balanced', tr: 'Sana yazsa hayır diyemeyeceğin biri var mı?', en: "Is there someone you couldn't say no to if they texted you?" },
  { id: 'exp_125', category: 'confession', intensity: 'balanced', tr: 'Şu an geri dönmek istediğin bir ilişki veya flört var mı?', en: "Is there a relationship or fling you'd want back right now?" },
  { id: 'exp_126', category: 'quick', intensity: 'soft', tr: 'Stalkladın mı? Evet / Hayır', en: 'Have you ever stalked someone? Yes / No' },
  { id: 'exp_127', category: 'quick', intensity: 'soft', tr: 'Ghostladın mı? Evet / Hayır', en: 'Have you ever ghosted someone? Yes / No' },
  { id: 'exp_128', category: 'quick', intensity: 'soft', tr: 'Ghostlandın mı? Evet / Hayır', en: 'Have you ever been ghosted? Yes / No' },
  { id: 'exp_129', category: 'quick', intensity: 'soft', tr: 'Eskiye döndün mü? Evet / Hayır', en: 'Have you ever gotten back with an ex? Yes / No' },
  { id: 'exp_130', category: 'quick', intensity: 'soft', tr: 'Fake hesaptan baktın mı? Evet / Hayır', en: 'Have you ever looked from a fake account? Yes / No' },
  { id: 'exp_131', category: 'quick', intensity: 'soft', tr: "Story'yi özellikle biri görsün diye attın mı? Evet / Hayır", en: 'Did you ever post a story specifically for one person to see? Yes / No' },
  { id: 'exp_132', category: 'quick', intensity: 'soft', tr: 'Mesaja bilerek geç cevap verdin mi? Evet / Hayır', en: 'Have you ever replied to a text late on purpose? Yes / No' },
  { id: 'exp_133', category: 'quick', intensity: 'soft', tr: 'Kıskandırmaya çalıştın mı? Evet / Hayır', en: 'Have you ever tried to make someone jealous? Yes / No' },
  { id: 'exp_134', category: 'quick', intensity: 'soft', tr: 'Birinin telefonunu gizlice kontrol ettin mi? Evet / Hayır', en: "Have you ever secretly checked someone's phone? Yes / No" },
  { id: 'exp_135', category: 'quick', intensity: 'soft', tr: 'Birinin eski sevgilisini stalkladın mı? Evet / Hayır', en: "Have you ever stalked someone's ex? Yes / No" },
  { id: 'exp_136', category: 'quick', intensity: 'soft', tr: "Arkadaşının crush'ından hoşlandın mı? Evet / Hayır", en: "Have you ever liked your friend's crush? Yes / No" },
  { id: 'exp_137', category: 'quick', intensity: 'soft', tr: 'Eski mesajları tekrar okudun mu? Evet / Hayır', en: 'Have you ever reread old messages? Yes / No' },
  { id: 'exp_138', category: 'quick', intensity: 'soft', tr: "Mesaj screenshot'ı arkadaşına attın mı? Evet / Hayır", en: 'Have you ever sent a message screenshot to a friend? Yes / No' },
  { id: 'exp_139', category: 'quick', intensity: 'soft', tr: "Birini mute'ladın mı? Evet / Hayır", en: 'Have you ever muted someone? Yes / No' },
  { id: 'exp_140', category: 'quick', intensity: 'soft', tr: 'Birini blocklayıp sonra unblockladın mı? Evet / Hayır', en: 'Have you ever blocked someone and then unblocked them? Yes / No' },
  { id: 'exp_141', category: 'quick', intensity: 'soft', tr: 'Birinden hoşlanırken hoşlanmıyormuş gibi yaptın mı? Evet / Hayır', en: "Have you ever pretended not to like someone while you did? Yes / No" },
  { id: 'exp_142', category: 'quick', intensity: 'soft', tr: "Bir date'e gitmekten son anda vazgeçtin mi? Evet / Hayır", en: 'Have you ever bailed on a date at the last minute? Yes / No' },
  { id: 'exp_143', category: 'quick', intensity: 'soft', tr: 'Birinin mesajını arkadaşlarınla birlikte cevapladın mı? Evet / Hayır', en: "Have you ever replied to someone's message together with your friends? Yes / No" },
  { id: 'exp_144', category: 'quick', intensity: 'soft', tr: "Birinin story'sini tekrar tekrar izledin mi? Evet / Hayır", en: "Have you ever rewatched someone's story over and over? Yes / No" },
  { id: 'exp_145', category: 'quick', intensity: 'soft', tr: 'Birinin seni fark etmesi için paylaşım yaptın mı? Evet / Hayır', en: 'Have you ever posted something just so someone would notice you? Yes / No' },
];

export const getQuestionsByFilter = (category?: ExposeMeCategory, intensity?: ExposeMeIntensity) =>
  EXPOSE_ME_QUESTIONS.filter((q) => (!category || q.category === category) && (!intensity || q.intensity === intensity));

export const getRandomExposeMeQuestion = (category?: ExposeMeCategory, intensity?: ExposeMeIntensity, excludeIds: string[] = []) => {
  const pool = EXPOSE_ME_QUESTIONS.filter((q) => (!category || q.category === category) && (!intensity || q.intensity === intensity) && !excludeIds.includes(q.id));
  return pool.length ? pool[Math.floor(Math.random() * pool.length)] : null;
};
